use_frameworks!

target 'PurchaseManager_Example' do
  pod 'PurchaseManager', :path => '../'
  
  target 'PurchaseManager_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.10'
    pod 'Nimble', '~> 5.1'
  end
end
